package aoc.twenty25

import kotlin.test.Test

class Day7Test {
    @Test
    fun `test part 1`() {
        kotlin.test.assertEquals(
            expected = 21,
            actual = Day7(testData).part1.solve(),
        )
    }

    @Test
    fun `test part 2`() {
        kotlin.test.assertEquals(
            expected = 40,
            actual = Day7(testData).part2.solve(),
        )
    }


    private val testData = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.trimIndent().split("\n")
}